version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: mrp_postgres
    restart: always
    environment:
      POSTGRES_USER: mrp_user
      POSTGRES_PASSWORD: mrp_password
      POSTGRES_DB: mrp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
